---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather
  annotations:
    "helm.sh/hook-weight": "3"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-weather
    spec:
      containers:
        - name: weatherapp-weather
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent
          env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                key: apikey
                name: {{ .Release.Name }}-weather
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http