apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mysql-init-job
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: {{ .Values.auth.db.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: auth-password
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql  # MySQL Service name or hostname
        - name: MYSQL_PORT
          value: "3306"  # MySQL port, default is 3306
        command: ["/bin/sh", "-c"]
        args:
        - |
          mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
          CREATE DATABASE IF NOT EXISTS weatherapp;
          CREATE USER 'authuser'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
          GRANT ALL PRIVILEGES ON weatherapp.* TO 'authuser'@'%';
          FLUSH PRIVILEGES;
          EOF
      restartPolicy: Never
