apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: weather
spec:
  encryptedData:
    apikey: AgBtApa5g9N2apRAPRaCTrwrWo+hu03wPtG8Yjv9UYoB6u6Lroju+Ec7Gq4YEF0/8RI4ubwaIW3Zlnn3EDrYNH13yQ7PwrP4N2arO6S8E0Z/8Cs94ITGMZJTztZkFg0tz3Zu+pM/VN0pBGH5W2k1TG/XSK5Ff+H5NUH+XNMo1EWKuVfnT6B4o/zsk4f5z7Kj8LeBlnPI36c/ij4/o5K4A8VkioEqnWJlyDpXin5wANFwPow1oprtUxqyQmI70Xq37FCkO9J88Z9PWooBPcmgb5HjipULzLnh7s8MUTWzyxzepeCWewE/HKQr/D6KmxI1OILEdoiM+7nUiEnPwCKEtiZPOeSEQ5eznpTQ/Q3ZYq+4C2dO+Uk4fSCMU5hMs6aNCMKMpSPH64CItWjl5D2bXQD5V/ffeeoTRyWcqmBA6dBxq/rhtGuocxFy6i2HboaBt7anPbfy+ymy5z1zlgEAIKen7ZyZgxwjH14ZItYufEv3LAi/n4fSoBOskHgUGXhPU7PsfPkfgLSdVhIVk9HY5C5orYWn4jkaBgDBh1UgvirvRrA3ziwnJZK5v94I/D0A+DYrcTLwFuxxdsu1ZxxnpA5M/SyL7KCT6zvygGrnBaeXnDcn2jzw+z8JBR2EsfDRhzWw/WEqpQZU9FEeHRCvw83prjAwdtwy7hK1KFA9eB7VwSDJXmhE8JaHyh/F1JDiK9ZzxYkxS4DJrvQ+gAwo3q3oC3/xeLxpl3gu1gRqBE7EfLvWhi8n7atl4udhGnYfGmo94g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: weather

